name = "card-app"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]

[triggers]
crons = ["0 * * * *", "0 5 * * *", "0 10 * * *", "20 15 * * *", "0 12 * * *"]

[observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "CACHE"
id = "23e104faac8545dcb39b9283bf368a9b"
